---
deployment:
  tasks:
    - export DEPLOYPATH=/home/badmint2/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp -R barang $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R midtrans $DEPLOYPATH
    - /bin/cp -R php $DEPLOYPATH